repos:
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
      language_version: python3
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.0
    hooks:
    - id: flake8
      exclude: benchmarks_vnn21|src/milp_network.py
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.950'
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports, --no-warn-unused-ignores]
        exclude: benchmarks_vnn21|dnnv
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: check-yaml
    -   id: check-json
    -   id: pretty-format-json
        args: [--no-sort-keys, --autofix]
-   repo: https://github.com/timothycrosley/isort
    rev: 5.8.0
    hooks:
    - id: isort
      args: ["--profile", "black"]
-   repo: local
    hooks:
    - id: pytest-check
      name: pytest-check
      entry: pytest
      language: system
      pass_filenames: false
      always_run: true
